### PR TITLE
prevent illegal thread access during refactoring

### PR DESCRIPTION
**Pull request by nittka**
If the score view is open and you try to rename the corresponding source file, trying to close the file in the view may throw an SWT exception (illegal thread access).

### CODE REVIEW

**Comment by nittka** [comment]
The other commits prepare the file view (i.e. Score and Audio) to be shown in the "Show In" menues and fix a Eclipse startup issue. The Score view did not properly load the last file that was open.

**Comment by thSoft** [comment]
Thanks for the renaming fix! Unfortunately, the Score view still does not show anything (deterministically) when it is open at startup and the Creating point-and-click hyperlinks job's "waiting for annotations to be loaded" phase hangs forever. If I close the Score view, the job disappears and if I reopen the Score view, it will display the score correctly.

**Comment by nittka** [comment]
I guess, it would be a good idea to make the wait loop behave better, anyway (actually wait and not just loop, as well as give up waiting at some point).
Maybe the file view should set the previous file only if it first gets the focus - the problem seems to be that this is done in the initialization, where not everything is set up yet.

**Comment by nittka** [comment]
OK, finally I found the problem. On starting up eclipse, jobs are scheduled all right, but waitForJob immediately returns (without the job having run). The resetAnnotationsJob is scheduled and some time later the renderJob and finally the createHyperlinksJob. However the resetAnnotationsJob cancels the renderJob (the intention being to cancel the previously running job, not the next one).
The new null check is basically a check if the renderJob has run at all (if not there will be no annotations and no reason for cancelling rendering).

**Comment by thSoft** [comment]
The issue is now fixed, great! Concurrency with mutable state FTW - NOT!

**Pull request merged**
