### PR TITLE
fix zoom binding

### PR DESCRIPTION
**Pull request by nittka**
This is a fix for https://github.com/thSoft/elysium/issues/126 introducing a context for the pdf view and restricting all key bindings to this context.

### CODE REVIEW

**Comment by nittka** [comment]
I realize that the context id should probably be different, as the view is a general pdf view...

**Comment by thSoft** [comment]
Thank you, I merged this but GitHub does not realize it.

**Comment by nittka** [comment]
I think you only merged the first commit. In a second one I renamed the context id (while forgetting the modify the name/description of the context). It's up to you whether this should be fixed or left as it is.

**Comment by thSoft** [comment]
I totally wanted to merge the second commit also, but I forgot to fetch. Now I merged it.

**Pull request closed without merging**
